apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-org1
  labels:
    type: local
spec:
  storageClassName: ibmc-block-gold
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"