apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-org2
  labels:
    type: local
spec:
  storageClassName: ibm-file-gold
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWrite
  hostPath:
    path: "/mnt/data"